loki:
  auth_enabled: false
  config: |-
    auth_enabled: false
    schema_config:
      configs:
        - from: 2025-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
    compactor:
      working_directory: /var/loki/compactor
      shared_store: filesystem
    limits_config:
      retention_period: 5m
    ingester:
      wal:
        enabled: true
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    server:
      http_listen_port: 3100
service:
  type: ClusterIP
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi